name: Build Windows 11
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update sources
        run: sudo apt -yq update
      - name: Install dependencies
        run: sudo apt -yq install qemu-system-x86 xorriso p7zip
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Create cache dir and temp dir for packer
        run: mkdir -p ${{ github.workspace }}/{.cache,.temp}
      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
      - name: Build vagrant box
        run: PACKER_CACHE_DIR=${{ github.workspace }}/.cache TMPDIR=${{ github.workspace }}/.temp make build-windows-11-24h2-uefi-libvirt
